src/apps/blogs/api/urls.py
from apps.blogs.api import routes

app_name = "api:blogs"

urlpatterns = routes.posts.router.urls

src/apps/blogs/pages/urls.py
from django.urls import path

from apps.blogs.pages.views import posts

app_name = "blogs"

urlpatterns = [
    path("", posts.list.View.as_view(), name="home"),
    path("posts/my/", posts.my.View.as_view(), name="posts_my"),
    path("posts/new/", posts.create.View.as_view(), name="post_create"),
    path("posts/<int:id>/", posts.detail.View.as_view(), name="post_detail"),
    path("posts/<int:id>/edit/", posts.edit.View.as_view(), name="post_edit"),
    path(
        "posts/<int:id>/delete/",
        posts.delete.View.as_view(),
        name="post_delete",
    ),
]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

app_title = "Django CQRS Demo"

urlpatterns = [
    path("ht/", include("health_check.urls")),
    path("admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
    path("", include("apps.users.pages.urls")),
    path("", include("apps.blogs.pages.urls")),
    path("api/", include("apps.users.api.urls")),
    path("api/", include("apps.blogs.api.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/blogs/models/post.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.blogs.models.enums import PostStatus


class Post(models.Model):
    """Post model."""

    class Meta:
        verbose_name = _("VN__POST")
        verbose_name_plural = _("VN__POSTS")

    title = models.CharField(
        max_length=255,  # noqa:  WPS432
        verbose_name=_("VN__TITLE"),
        help_text=_("HT__TITLE"),
    )

    content = models.TextField(  # noqa: WPS110
        verbose_name=_("VN__CONTENT"),
        help_text=_("HT__CONTENT"),
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("VN__CREATED_AT"),
        help_text=_("HT__CREATED_AT"),
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_("VN__UPDATED_AT"),
        help_text=_("HT__UPDATED_AT"),
    )

    status = models.CharField(
        max_length=10,
        choices=PostStatus.choices,
        verbose_name=_("VN__STATUS"),
        help_text=_("HT__STATUS"),
    )

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        models.CASCADE,
        verbose_name=_("VN__AUTHOR"),
        help_text=_("HT__AUTHOR"),
    )

    def __str__(self):
        """Text representation."""
        return self.title

src/apps/blogs/api/routes/posts.py
from apps.blogs.api.views import posts
from apps.core.api.routers import ActionsRouter

router = ActionsRouter()
router.get("posts", posts.list.View.as_view())
router.post("posts", posts.create.View.as_view())
router.get("posts/<int:pk>", posts.retrieve.View.as_view())
router.delete("posts/<int:pk>", posts.delete.View.as_view())
router.patch("posts/<int:pk>", posts.update.View.as_view())

src/apps/blogs/templates/posts/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>New post</title>
{% endblock title %}

<h1>New post</h1>
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
{% endblock %}

src/apps/blogs/templates/posts/detail.html
{% extends "base.html" %}

{% block title %}
    <title>
        {% if instance %}
            {{ instance.title }}
        {% else %}
            Post not found
        {% endif %}
    </title>
{% endblock title %}

{% block content %}
    <div class="col-md-8">
        {% if instance %}
            <div>
                <h1>{{ instance.title }}</h1>
                <p class="text-muted">{{ instance.author }} | {{ instance.created_at }}</p>
                <p class="card-text ">{{ instance.content | safe }}</p>
            </div>
        {% else %}
            <h1>Post not found</h1>
        {% endif %}
    </div>
{% endblock content %}

src/apps/blogs/templates/posts/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Edit post</title>
{% endblock title %}

<h1>Edit post</h1>
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save changes</button>
        <form class="d-inline" method="POST" action="{% url 'blogs:post_delete' form.instance.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </form>
{% endblock %}

src/apps/blogs/templates/posts/list.html
{% extends "base.html" %}
{% block content %}
    <div class="col-md-8">
        {% for post in instances %}
            <div class="card mb-4">
                <div class="card-body{% if post.status == "draft" %} text-muted{% endif %}">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_at }} </p>
                    <p class="card-text">{{ post.content|slice:":200" }}</p>
                    <a href="{% url 'blogs:post_detail' post.id %}" class="btn btn-primary">Read More &rarr;</a>
                    {% if post.author == user %}
                        <a href="{% url 'blogs:post_edit' post.id %}" class="btn btn-primary">Edit</a>
                        <form class="d-inline" method="POST" action="{% url 'blogs:post_delete' post.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}